closing out #15990; the snapshots on the mirrors now have md5sum's distributed along side, and this adds the support to emerge-webrsync. see the changelog for all the specifics, but closes out the complaints in 15990 and makes things a bit friendly to the user.

diff --git a/bin/emerge-webrsync b/bin/emerge-webrsync
--- a/bin/emerge-webrsync
+++ b/bin/emerge-webrsync
@@ -5,7 +5,7 @@
 # Author: Karl Trygve Kalleberg <karltk@gentoo.org>
 # Rewritten from the old, Perl-based emerge-webrsync script
 
-GENTOO_MIRRORS="$(/usr/lib/portage/bin/portageq gentoo_mirrors)"
+GENTOO_MIRRORS="${GENTOO_MIRRORS} $(/usr/lib/portage/bin/portageq gentoo_mirrors)"
 PORTDIR="$(/usr/lib/portage/bin/portageq portdir)"
 FETCHCOMMAND="$(/usr/lib/portage/bin/portageq envvar FETCHCOMMAND)"
 USERLAND="$(/usr/lib/portage/bin/portageq envvar USERLAND)"
@@ -19,7 +19,6 @@ cd "$DISTDIR"
 
 found=0
 attempts=0
-download=1
 if [ "$1" == "-v" ] ; then
 	wgetops=
 else	
@@ -32,8 +31,14 @@ else
 	fi
 fi
 
-if [ "$1" == "-n" ] ; then
-	download=0
+if type -p md5sum > /dev/null; then
+	md5_com='md5sum -c "${FILE}.md5sum"'
+elif type -p md5 > /dev/null; then
+	md5_com='[ "$(md5 -q ${FILE})" == "$(cut -d \  -f 1 ${FILE}.md5sum)" ]'
+else
+	echo "warning, unable to do md5 verification of the snapshot!"
+	echo "no suitable md5/md5sum binary was found!"
+	md5_com='true'
 fi
 
 sync_local() {
@@ -68,25 +73,58 @@ while (( $attempts <  40 )) ; do
 		year=$(date -d "-$attempts day" +"%Y")
 	fi
 
-	FILE="portage-${year}${month}${day}.tar.bz2"
-
-	if [ -f "$FILE" ] && [ $download == 0 ] ; then
-		sync_local
-		exit 0
-	fi
-
-	for i in $GENTOO_MIRRORS ; do 
-		URI="${i}/snapshots/$FILE"
-		rm -f "$FILE"
+	FILE_ORIG="portage-${year}${month}${day}.tar.bz2"
 		
-		if (eval "$FETCHCOMMAND $wgetops") && [ -s "$FILE" ]; then
+	got_md5=0
+
+	if [  ! -e "${FILE_ORIG}.md5sum" ]; then
+		FILE="${FILE_ORIG}.md5sum"
+		for i in $GENTOO_MIRRORS ; do 
+			URI="${i}/snapshots/${FILE}"
+			if (eval "$FETCHCOMMAND $wgetops") && [ -s "${FILE}" ]; then
+				got_md5=1
+				break
+			fi
+		done
+	else
+		got_md5=1
+	fi
+	FILE="${FILE_ORIG}"
+
+	if (($got_md5 == 0 )); then
+		echo "unable to fetch md5sum, no way to detect corruption.  bailing"
+		exit 1
+	elif [ -s "${FILE}" ]; then
+		if eval "$md5_com"; then
+			echo "existing snapshot $FILE is correct, using it"
 			sync_local
 			echo
-			echo " *** Completed websync, please now perform a normal rsync if possible."
-			echo "     Update is current as of the of YYYYMMDD: ${year}${month}${day}"
-			echo
+			echo " *** Reused snapshot $FILE"
+			ehco 
 			exit 0
+		else
+			rm $FILE
 		fi
+	fi
+	
+	for i in $GENTOO_MIRRORS ; do
+		URI="${i}/snapshots/$FILE"
+		rm -f "$FILE"
+		if (eval "$FETCHCOMMAND $wgetops") && [ -s "$FILE" ]; then
+			if ! eval "$md5_com"; then
+				echo "md5 failed on $FILE"
+				rm ${FILE}
+				continue
+			else
+				sync_local
+				echo
+				echo " *** Completed websync, please now perform a normal rsync if possible."
+				echo "     Update is current as of the of YYYYMMDD: ${year}${month}${day}"
+				echo
+				exit 0
+			fi
+		fi
+
 	done
 	attempts=$[attempts+1]
 done
