add a sanity check for diff before using it #48184

diff --git a/bin/etc-update b/bin/etc-update
--- a/bin/etc-update
+++ b/bin/etc-update
@@ -12,7 +12,7 @@
 
 export PORTAGE_CALLER="etc-update"
 
-if [ $(/usr/lib/portage/bin/portageq envvar USERLAND) = BSD ] ; then
+if type -p gsed >/dev/null ; then
 	function sed() { gsed "$@"; }
 fi
 
@@ -33,8 +33,16 @@ function scan() {
 	mkdir ${TMP}/files || die "Failed mkdir command!" 1
 	count=0
 	input=0
-	
-	for path in ${CONFIG_PROTECT}; do if [ -d ${path} ]; then
+
+	# Sanity check to make sure diff exists and works
+	if ! diff -v &>/dev/null ; then
+		echo "ERROR: 'diff' does not seem to work, aborting"
+		exit 1
+	fi
+
+	for path in ${CONFIG_PROTECT} ; do
+		[ ! -d ${path} ] && continue
+
 		ofile=""
 		for file in `find ${path}/ -iname "._cfg????_*" |
 			   sed -e "s:\(^.*/\)\(._cfg*_\)\(/.*$\):\1\2\3\%\2\%\3:" |
@@ -88,7 +96,7 @@ function scan() {
 				opath="${rpath}"
 			fi
 		done
-	fi; done
+	done
 
 }
 
