clean up and allow for selectable compression methods #9870

diff --git a/bin/prepinfo b/bin/prepinfo
--- a/bin/prepinfo
+++ b/bin/prepinfo
@@ -1,5 +1,5 @@
 #!/bin/bash
-# Copyright 1999-2004 Gentoo Foundation
+# Copyright 1999-2005 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
 # $Header$
 
@@ -15,19 +15,32 @@ fi
 
 [ ! -d "${z}" ] && exit 0
 
-rm -f "${z}"/{dir,dir.info,dir.info.gz}
+rm -f "${z}"/dir{,.old}{,.info{,.gz,.bz2,.Z}}
+
+PORTAGE_COMPRESS=${PORTAGE_COMPRESS:-gzip}
+PORTAGE_COMPRESS_FLAGS=${PORTAGE_COMPRESS_FLAGS:--9}
+if [ -z "${PORTAGE_COMPRESS_SUFFIX}" ] ; then
+	case ${PORTAGE_COMPRESS} in
+		gzip)  suffix="gz";;
+		bzip2) suffix="bz2";;
+		*)     echo "prepinfo: error fixing links: please set PORTAGE_COMPRESS_SUFFIX in make.conf" 1>&2
+		       exit 1;;
+	esac
+fi
+
+echo "info: ${PORTAGE_COMPRESS} ${PORTAGE_COMPRESS_FLAGS}"
 
 for x in `find "${z}"/ \( -type f -or -type l \) -maxdepth 1 -mindepth 1 2>/dev/null` ; do
 	if [ -L "${x}" ] ; then
 		# Symlink ...
-		mylink="${x}"
-		linkto="`readlink "${x}"`"
+		mylink=${x}
+		linkto=$(readlink "${x}")
 
-		if [ "${linkto##*.}" != "gz" ] ; then
-			linkto="${linkto}.gz"
+		if [ "${linkto##*.}" != "${suffix}" ] ; then
+			linkto="${linkto}.${suffix}"
 		fi
-		if [ "${mylink##*.}" != "gz" ] ; then
-			mylink="${mylink}.gz"
+		if [ "${mylink##*.}" != "${suffix}" ] ; then
+			mylink="${mylink}.${suffix}"
 		fi
 
 		echo "fixing GNU info symlink: ${mylink##*/}"
@@ -37,9 +50,9 @@ for x in `find "${z}"/ \( -type f -or -type l \) -maxdepth 1 -mindepth 1 2>/dev/
 			rm -f "${x}"
 		fi
 	else
-		if [ "${x##*.}" != "gz" ] ; then
-			echo "gzipping GNU info page: ${x##*/}"
-			gzip -f -9 "${x}"
+		if [ "${x##*.}" != "${suffix}" ] ; then
+			echo "compressing GNU info page: ${x##*/}"
+			"${PORTAGE_COMPRESS}" ${PORTAGE_COMPRESS_FLAGS} -f "${x}"
 		fi
 	fi
 done
diff --git a/bin/prepman b/bin/prepman
--- a/bin/prepman
+++ b/bin/prepman
@@ -1,5 +1,5 @@
 #!/bin/bash
-# Copyright 1999-2004 Gentoo Foundation
+# Copyright 1999-2005 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
 # $Header$
 
@@ -11,35 +11,50 @@ fi
 
 [ ! -d "${z}" ] && exit 0
 
+PORTAGE_COMPRESS=${PORTAGE_COMPRESS:-gzip}
+PORTAGE_COMPRESS_FLAGS=${PORTAGE_COMPRESS_FLAGS:--9}
+if [ -z "${PORTAGE_COMPRESS_SUFFIX}" ] ; then
+	case ${PORTAGE_COMPRESS} in
+		gzip)  suffix="gz";;
+		bzip2) suffix="bz2";;
+		*)     echo "prepman error: please set PORTAGE_COMPRESS_SUFFIX in make.conf" 1>&2
+		       exit 1;;
+	esac
+fi
+
+if [ -z "${prepallman_banner}" ] ; then
+	echo "man: ${PORTAGE_COMPRESS} ${PORTAGE_COMPRESS_FLAGS}"
+fi
+
 for x in `find "${z}"/ -type d 2>/dev/null` ; do
 	for y in `find "${x}"/ \( -type f -or -type l \) ! -name '.keep' -maxdepth 1 -mindepth 1 2>/dev/null` ; do
 		if [ -L "${y}" ] ; then
 			# Symlink ...
-			mylink="${y}"
-			linkto="`readlink "${y}"`"
-			
+			mylink=${y}
+			linkto=$(readlink "${y}")
+
 			# Do NOT change links to directories
 			if [ -d "${z}/${linkto}" ] ; then
 				continue
 			fi
-			
-			if [ "${linkto##*.}" != "gz" ] ; then
-				linkto="${linkto}.gz"
+
+			if [ "${linkto##*.}" != "${suffix}" ] ; then
+				linkto="${linkto}.${suffix}"
 			fi
-			if [ "${mylink##*.}" != "gz" ] ; then
-				mylink="${mylink}.gz"
+			if [ "${mylink##*.}" != "${suffix}" ] ; then
+				mylink="${mylink}.${suffix}"
 			fi
 
-			echo "fixing man page symlink: ${mylink##*/}"
+			echo "   link fixed ${mylink##*/}"
 			ln -snf "${linkto}" "${mylink}"
 			if [ "${y}" != "${mylink}" ] ; then
-				echo "removing old symlink: ${y##*/}"
+				echo "   link removed ${y##*/}"
 				rm -f "${y}"
 			fi
 		else
-			if [ "${y##*.}" != "gz" ] && [ ! -d "${y}" ]; then
-				echo "gzipping man page: ${y##*/}"
-				gzip -f -9 "${y}"
+			if [ "${y##*.}" != "${suffix}" ] && [ ! -d "${y}" ] ; then
+				echo "   compressing ${y##*/}"
+				"${PORTAGE_COMPRESS}" ${PORTAGE_COMPRESS_FLAGS} -f "${y}"
 			fi
 		fi	
 	done
